NurseVolunteeringSystem/Controllers/SuburbController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NurseVolunteeringSystem.Models;
using System.Linq;

namespace NurseVolunteeringSystem.Controllers
{
    public class SuburbController : Controller
    {
        private readonly AppDBContext _context;

        public SuburbController(AppDBContext context)
        {
            _context = context;
        }

        
        public IActionResult Index()
        {
            var suburbs = _context.Suburb
                .Where(s => s.Status == "Active")
                .Include(s => s.City)
                .ToList();

            ViewBag.Suburbs = suburbs;
            return View(suburbs);
        }

        
        public IActionResult Create()
        {
            ViewBag.Cities = _context.City.ToList();
            return View();
        }

        
        [HttpPost]
        public IActionResult Create(Suburb model)
        {
            if (ModelState.IsValid)
            {
                var existingCity = _context.City.FirstOrDefault(c => c.CityName == model.City.CityName);

                if (existingCity != null)
                {
                    model.City = existingCity; 
                }

                _context.Suburb.Add(model);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Cities = _context.City.ToList();
            return View(model);
        }

        
        public IActionResult Edit(int id)
        {
            var suburb = _context.Suburb.Include(s => s.City).FirstOrDefault(s => s.SuburbID == id);

            if (suburb == null)
            {
                return NotFound();
            }

            ViewBag.Cities = _context.City.ToList();
            return View(suburb);
        }

       
        [HttpPost]
        public IActionResult Edit(Suburb model)
        {
            if (ModelState.IsValid)
            {
                var existingCity = _context.City.FirstOrDefault(c => c.CityName == model.City.CityName);

                if (existingCity != null)
                {
                    model.City = existingCity; 
                }

                _context.Suburb.Update(model);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Cities = _context.City.ToList();
            return View(model);
        }

        
        public IActionResult Details(int id)
        {
            var suburb = _context.Suburb.Include(s => s.City).FirstOrDefault(s => s.SuburbID == id);
            if (suburb == null)
            {
                return NotFound();
            }
            return View(suburb);
        }

        

        public IActionResult Delete(int id)
        {
            var suburb = _context.Suburb.Include(s => s.City).FirstOrDefault(s => s.SuburbID == id);
            if (suburb == null)
            {
                return NotFound();
            }
            return View(suburb);
        }
        
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var suburb = _context.Suburb.Find(id);
            if (suburb != null)
            {
                suburb.Status = "In-Active";
                _context.Suburb.Update(suburb);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

NurseVolunteeringSystem/Areas/Manager/Views/Shared/_ManagerLayout.cshtml
@using Microsoft.AspNetCore.Http;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HelpingHands</title>
    
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @*Font awesome added for icons*@
    <link href="~/fontawesome/css/all.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary text-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Manager" asp-controller="Home" asp-action="HomePage">Helping Hands</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Manager" asp-controller="ChronicCondition" asp-action="create">Manage Conditions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Manager" asp-controller="City" asp-action="create">Manage City</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Manager" asp-controller="Suburb" asp-action="create">Manage Suburbs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Manager" asp-controller="Contract" asp-action="ListContracts">List contracts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Manager" asp-controller="Contract" asp-action="ContractsByDate">contracts by date</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Manager" asp-controller="Contract" asp-action="ListAssignedContracts">Assigned contracts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Manager" asp-controller="PrefferedSuburb" asp-action="ListSuburbs">Suburbs Per Nurse</a>
                        </li>

                        
                        
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                @Context.Session.GetString("Names")
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item btn btn-danger" asp-controller="Account" asp-action="Logout" asp-area="">Logout</a>
                            </div>
                        </li>


                    </ul>



                </div>
               
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3 bg-white">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-warning">
        <div class="container">
            &copy; 2023 - Helping Hands - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>