NurseVolunteeringSystem/Controllers/CareContractController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NurseVolunteeringSystem.Models;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace NurseVolunteeringSystem.Controllers
{
    public class CareContractController : Controller
    {
        private readonly AppDBContext _context;

        public CareContractController(AppDBContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var careContracts = await _context.CareContract.Include(c => c.Suburb).ToListAsync();
            return View(careContracts);
        }


        public IActionResult Create()
        {
            ViewBag.Suburbs = _context.Suburb.ToList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CareContract careContract)
        {
            if (ModelState.IsValid)
            {
                careContract.ContractDate = DateTime.Today;
                _context.CareContract.Add(careContract);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            foreach (var modelState in ModelState.Values)
            {
                foreach (var error in modelState.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.ErrorMessage);
                }
            }

            ViewBag.Suburbs = _context.Suburb.ToList();
            return View(careContract);
       
        }

        // GET: CareContract/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var careContract = await _context.CareContract.FindAsync(id);
            if (careContract == null)
            {
                return NotFound();
            }

            ViewBag.Suburbs = _context.Suburb.ToList();
            return View(careContract);
        }

        // POST: CareContract/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CareContract careContract)
        {
            if (id != careContract.CareContractID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(careContract);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CareContractExists(careContract.CareContractID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Suburbs = _context.Suburb.ToList();
            return View(careContract);
        }

        // GET: CareContract/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var careContract = await _context.CareContract
                .Include(c => c.Suburb)
                .FirstOrDefaultAsync(m => m.CareContractID == id);

            if (careContract == null)
            {
                return NotFound();
            }

            return View(careContract);
        }

        // POST: CareContract/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var careContract = await _context.CareContract.FindAsync(id);
            careContract.DeleteStatus = "Deleted";
            _context.CareContract.Update(careContract);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CareContractExists(int id)
        {
            return _context.CareContract.Any(e => e.CareContractID == id);
        }
    }
}

NurseVolunteeringSystem/Areas/Nurse/Views/Shared/_NurseLayout.cshtml
@using Microsoft.AspNetCore.Http;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HelpingHands</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary text-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="Nurse" asp-controller="Home" asp-action="HomePage">Helping Hands</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="PreferredSuburb" asp-action="AddPreferredSuburb" asp-area="Nurse">Add preferred Suburb</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="CareContract" asp-action="ListContracts" asp-area="Nurse">Preferred contracts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="CareContract" asp-action="ListAssignedContracts" asp-area="Nurse">Assigned contracts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="CareContract" asp-action="ListClosedContracts" asp-area="Nurse">Closed contracts</a>
                        </li>
                        &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;
                        &nbsp;
                        


                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                @Context.Session.GetString("Names")
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" asp-controller="Home" asp-action="UpdateNursePersonalInfo" asp-area="Nurse">Update  personal info</a>
                                <a class="dropdown-item" asp-controller="Home" asp-action="ChangePassword" asp-area="Nurse">Change Password</a>
                                <a class="dropdown-item btn btn-danger" asp-controller="Account" asp-action="Logout" asp-area="">Logout</a>
                            </div>
                        </li>


                    </ul>
                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - NurseVolunteeringSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>